spring:
  web:
    resources:
      static-locations: classpath:none/

  datasource:
    url: jdbc:mysql://jiacai.cluster-ro-ch4gzirclaxq.ap-southeast-1.rds.amazonaws.com:3306/jiacai
    username: admin
    password: Lottery123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: ''
    timeout: 5000
  rabbitmq:
    host: '127.0.0.1'
    port: 5672
    username: 'rabbitmq_xingyun'
    password: 'rabbitmq_xingyun456'
    virtual-host: /lottery
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
    cache:
      connection:
        mode: connection
        size: 32
      channel:
        size: 8
        checkout-timeout: 15000
    requested-channel-max: 16

logging:
  level:
    springfox: error
    com.xingyun.easypaycommon.dao.mapper: info
    org.springframework.context.annotation.ClassPathBeanDefinitionScanner: info
    org.redisson.connection: error
  config: /work/product/config/logback-api.xml

project:
  self_reward: false
  job:
    production: true

pay:
  shark:
    notify_url: https://cdnapi.ckckzz.com/pay/callback/shark
  douma:
    notify_url: https://cdnapi.ckckzz.com/pay/callback/douma
  yunyin:
    notify_url: https://cdnapi.ckckzz.com/pay/callback/yunyin
  kdou:
    notify_url: https://cdnapi.ckckzz.com/pay/callback/kdou
  jinqiantong:
    notify_url: https://cdnapi.ckckzz.com/pay/callback/jinqiantong
  yunpay:
    notify_url: https://cdnapi.ckckzz.com/pay/callback/yunpay







